### ISSUE TITLE
Alias resolution doesn't work with & $variable invocation (like in PS pager use)

### ISSUE THREAD

**Issue by rjmholt** [mikebattista/PowerShell-WSL-Interop#17]
@mikebattista raised this issue offline today. It's an edge case, but strikes when `$env:PAGER` is set to `less` in PowerShell.

### Reproduction
```powershell
$mysteriousCommand = 'grep'

& $mysteriousCommand .log
```

### Expected Behaviour
Runs `grep` via WSL.

### Actual Behaviour
Is unable to resolve the alias, since `$MyInvocation.InvocationName` is unhelpfully `&`...

### Proposed Solution
Ideally, PowerShell should create more information here, but to work around this, the most straightforward solution might be to create functions rather than aliases, which wrap `Invoke-WslCommand`:

```powershell
function grep
{
    Invoke-WslCommand -CommandName grep ...
}
```

**Comment by mikebattista** [comment]
Thanks for filing. I am aware of this issue and actually have some code in place to detect when & is the InvocationName and then resolve variables to their values. Are you using the latest code from master?

There is one outstanding issue that I'm trying to resolve that only occurs when using this code in a script module. The broken scenario is $env:PAGER = less, then call 'help' which will honor the PAGER. I think the script module introduces some scoping issues that prevent me from resolving the $pagerCommand variable it uses. When the code is just part of your profile, the code in master can resolve $pagerCommand no problem.

Are you adding the ps1 file to your profile, or using the alpha script module that I published?

Also FYI I had function wrappers originally, but really want to stick with aliases because the performance of loading many commands is drastically better with aliases. See #14 for details.

Given that the key scenario here is to add the import command to your profile, I'd really like to keep profile loading as fast as possible.

**Comment by mikebattista** [comment]
I switched back to function wrappers for now since it's not currently possible to resolve the 'help' scenario as a script module. For the majority of scenarios, the performance overhead relative to aliases should be negligible.

If $MyInvocation is updated to be more useful here, I will switch back.

**Comment by rjmholt** [comment]
> If $MyInvocation is updated to be more useful here, I will switch back.

You would probably need to condition it on PowerShell version, but if you were only targeting the version of PowerShell after such a change is made it would be possible to guarantee.

> performance of loading many commands is drastically better with aliases

Do you mean that simply defining the functions in PowerShell is much slower than defining the aliases? If so, that feels like an issue in PowerShell we should address.

**Comment by mikebattista** [comment]
I'm dynamically generating the function wrappers with Invoke-Expression, and executing that for many commands (my stress test is 800) takes multiple seconds, compared to just calling Set-Alias 800  times which takes 0.1s.

This is more of a stress test than a realistic scenario though which is why I think for the majority of realistic use cases, the performance overhead of calling Invoke-Expression for whatever set of the commands the user imports should be negligible.

If $MyInvocation were more useful though with &, the alias approach would be ideal for this scenario with effectively no overhead regardless of the number of commands imported.

**Comment by rjmholt** [comment]
> I'm dynamically generating the function wrappers with Invoke-Expression

Ah! I can imagine Invoke-Expression is heavyweight under the hood. I'll look into whether there's a faster way. It might be possible to do it faster by doing something like:

```powershell
Set-Item "function:$commandName" ([scriptblock]::Create("Invoke-WslCommand -CommandName $commandName"))
```
